version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-meta
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Moonie17*
      POSTGRES_DB: used_car
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase
    container_name: metabase
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: used_car
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: Gulali97
      MB_DB_HOST: postgres-meta
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
